### ISSUE TITLE
You can create and for nukkit ? :)

### ISSUE THREAD

**Issue by ghost** [Creeperface01/ColorMatch#15]
Hello.

You can create and for nukkit ?

**Comment by Creeperface01** [comment]
Yes i can :D

**Comment by Creeperface01** [comment]
But idk. Because there are couple of things i can do :D

**Comment by ghost** [comment]
Have nukkit MiniGames plugins? I created one server with nukkit and i planned for MiniGames :) Idk.. Factions not exist for nukkit for factions server. And Idk create on my server :/

**Comment by Creeperface01** [comment]
Now im porting my private minigames

**Comment by ghost** [comment]
And pls give me MiniGames plugin? :)

**Comment by Creeperface01** [comment]
i made new branch called java :)
