### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [Creeperface01/ColorMatch#2]
Hi,
- Game start / stop commands do not work and crash
- win and loss no message
- colors unchanged given wool
  AND
  The game ends, but the arena does not reset > http://i.hizliresim.com/DR8oqy.png

**Comment by ghost** [comment]
in addition
http://i.hizliresim.com/8b9EDV.png

**Comment by Creeperface01** [comment]
thx for reporting :) but some errors i fixed in last version so download version 1.0.1
and floor resets when new game starts.

**Comment by ghost** [comment]
Thanks bro
