### ISSUE TITLE
EndMessage ?

### ISSUE THREAD

**Issue by arsenicblast** [Creeperface01/ColorMatch#28]
How am I supposed to add a EndMessage or when a player won
I opened Colormatch>Arenas>ColorMatch.yml and edit the finish_msg_levels:
and also tried ColorMatch>Languages>English.yml and edit the #end game message:  and end_game:
But nothing happened. It doesnt show anything when a player won
If my method is wrong,can someone pls teach me how ?

**Comment by Creeperface01** [comment]
Sorry this plugin is currently outdated, I'll try to update it in summer

**Comment by arsenicblast** [comment]
Dude other servers has end message of their colormatch and Im pretty sure they are using your plugin

**Comment by Creeperface01** [comment]
Java is different that PHP version so maybe its the cause

**Comment by Creeperface01** [comment]
https://nukkitx.com/resources/colormatch.196/
