### ISSUE TITLE
Pocketmine ColorMatch scoreboard request

### ISSUE THREAD

**Issue by BlueWhaleYT** [Creeperface01/ColorMatch#36]
Hi there,
I know this is original of Nukkit.I downloaded a Pocketmine version.Can the author make a scoreboard for this plugin?Thanks.

**Comment by Creeperface01** [comment]
Php version is no longer supported  by me

**Comment by BlueWhaleYT** [comment]
so can you tell me who is the leader of php colormatch.

**Comment by Creeperface01** [comment]
Nobody, feel free to fork it

**Comment by BlueWhaleYT** [comment]
I don't know how to edit and will even break it.
