### ISSUE TITLE
I dont know how to use it

### ISSUE THREAD

**Issue by ZGamerOficial** [Creeperface01/ColorMatch#4]
First i put /cm create arena1 then /cm set arena1 then in the chat done without /.but when i put /cm start arena1 the chat show me arena doesnt exists.I ready reload the server but nothing happen.can you help me? Pls.thanks! And sorry for my bad english.i speak spanish.

**Comment by Creeperface01** [comment]
Have you set "enabled" to true?

**Comment by ebebebeb** [comment]
ME TOO;@SoyPro

**Comment by ebebebeb** [comment]
Oh sorry@creeperface01

**Comment by ebebebeb** [comment]
I change false--true.  i put /cm start abcdef .but areans doesnt sxist pls help me ! I dont well English @Creeperface01

**Comment by Creeperface01** [comment]
See example config or maybe restart server

**Comment by Creeperface01** [comment]
And this is not fórum.
