### ISSUE TITLE
Pls Help me i dont know my mistake

### ISSUE THREAD

**Issue by ebebebeb** [Creeperface01/ColorMatch#5]
I PUT /cm create abcd>>>/cm set abcd>>>>joinsign without /. And then break sign.>>>>done without/.then, I touch sign but --Chat--[CM]Arena is in setup mode! Pls Usage pls

**Comment by Creeperface01** [comment]
Write this on pocketmine.

**Comment by Creeperface01** [comment]
thx it was really bug sorry :D i fixed it in version 1.1
