### ISSUE TITLE
I ready put al commands

### ISSUE THREAD

**Issue by ZGamerOficial** [Creeperface01/ColorMatch#6]
It doesnt work.i have ready put /cm start arena1 and i change to true but when i put /cm start arena1 nothing happen,in the chat nothing show me.fix this please this plugin is awesome

**Comment by Creeperface01** [comment]
Ok i look at it but for now try to join to the arena and type: /cm start

**Comment by ZGamerOficial** [comment]
Yes!now yes but the console show me:[Server[19:56:09][Server thread/CRITICAL]: Could not execute task ColorMatch/Arena/ArenaShedule/: Undefined offset: 2
[Server][19:56:09][Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 2" (E_NOTICE) in"/plugin-1319.phar/src/ColorMatch/Arena/Arena" at line 516

Please fix this!thanks!

**Comment by Creeperface01** [comment]
thx

**Comment by Creeperface01** [comment]
you must have old version of plugin download version 1.1 from github

**Comment by ZGamerOficial** [comment]
Yes i put it.but the lobby automatic build or i have to build it?

**Comment by Creeperface01** [comment]
No :D i mean you must use latest version of the plugin xD and which lobby? Only floor is automatic

**Comment by ZGamerOficial** [comment]
But when i put /cm join arena1 the game teleport me to colormatch world and i appear in the sky and i fell to floor then i put /cm start arena1 and again i appear in the sky but with a lot of wool and then i fell to the floor and this wool disappear.But the isnt a lobby with blocks because players when join can go to others ways.I have to put a map or not?

**Comment by ZGamerOficial** [comment]
The lobby when players appear cant go out

**Comment by Creeperface01** [comment]
You must build it
